import Image from "next/image";

/**
 * Article image wrapper that shows an "AI" corner badge
 * when the image was generated by an AI service (Pollinations).
 * Uses next/image with fill layout — the parent container must have
 * a defined size and `position: relative`.
 */
export function ArticleImage({
  src,
  alt = "",
  className = "",
  containerClassName = "",
}: {
  src: string;
  alt?: string;
  className?: string;
  containerClassName?: string;
}) {
  const isAI = src.includes("pollinations.ai");

  return (
    <div className={`relative ${containerClassName}`}>
      <Image
        src={src}
        alt={alt}
        fill
        className={className}
        unoptimized
      />
      {isAI && (
        <span className="absolute top-1 right-1 bg-black/60 text-white text-[9px] font-semibold leading-none px-1.5 py-1 rounded-sm uppercase tracking-wide">
          AI
        </span>
      )}
    </div>
  );
}
